const mongoose = require('mongoose');
const {Schema, model} = mongoose


const projectSchema = new mongoose.Schema({
    user: {
    // ObjectId=(generated by MongoDB)
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
    },
    name: {
        type: String,
        required: true
     },
     description: {
        type: String,
        required: true
     }
});

const Project = mongoose.model('Project', projectSchema);
module.exports = Project;