const mongoose = require('mongoose');


const taskSchema = new mongoose.Schema({
    // 1 project -> many tasks
    // field for project belongs to
    project: {
    // ObjectId=(generated by MongoDB)
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Project',
    required: true
    },
    title: {
        type: String,
        required: true
     },
     description: {
        type: String,
        required: true
     },
     status:{
        type: String,
        // any other you try to do validate will be validation error
        // value of status
        enum:['todo', 'in-progress', 'done'],
      
     }
     },{
      // createdAt and updatedAt automatically
      timestamps:true 
});

const Task = mongoose.model('Task', taskSchema);
module.exports = Task;






// by abraham

// const mongoose = require("mongoose");
// const taskSchema = new mongoose.Schema({
//   project: {
//     type: mongoose.Schema.Types.ObjectId,
//     ref: "Project",
//     required: true,
//   },
//   title: {
//     type: String,
//     required: true,
//   },
//   description: {
//     type: String,
//     required: true,
//   },
//   status: {
//     type: String,
//     enum: ['todo', 'in-progress', 'done']
//   }
// });
// const Task = mongoose.model("Task", taskSchema);
// module.exports = Task;